add_executable(diff_tests
    diff_report_test.cpp
    diff_match_test.cpp
    path_matching_test.cpp
    diff_moves_test.cpp
    move_detection_test.cpp
    diff_fields_test.cpp
    diff_nested_test.cpp
    diff_populate_test.cpp
    field_diffing_test.cpp
    diff_sort_test.cpp
    diff_text_test.cpp
)
target_link_libraries(
    diff_tests
    PRIVATE
    libparsex
    GTest::gtest
    GTest::gtest_main
)
gtest_discover_tests(diff_tests)
